version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  nginx:
    container_name: my_nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ${LOCAL_CODE_PATH}:/var/www:rw
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    networks:
      - frontend

  phpfpm:
    container_name: my_phpfpm
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_SSH2=${PHP_FPM_INSTALL_SSH2}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
    expose:
      - "9000"
    volumes:
      - ${LOCAL_CODE_PATH}:/var/www:cached
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    networks:
      - frontend
      - backend

  mysql:
    container_name: my_mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    ports:
      - "3306:3306"
    volumes:
      - ${LOCAL_DATA_PATH}/mysql:/var/lib/mysql
      - ./log/mysql/:/var/log/mysql/
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - backend

  redis:
    container_name: my_redis
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ${LOCAL_DATA_PATH}/redis:/data
    networks:
      - backend

